### ISSUE TITLE
Do you mind write some comments about how to use your bash script called "problem.sh"?

### ISSUE THREAD

**Issue by y1275963** [haoel/leetcode#45]
Hi,

I want to work on my own like your project. And I also want to place the problem on top of my own answer. But I don't know how to use the scraper you wrote.( Although it is only one line..) Do you mind write a comment or a demonstration about to how to use this script called "problem.sh"?

Cheers!

**Comment by haoel** [comment]
As your wish, I rewrote the script! and introduce a new script named `comment.sh` you can take a look the code change: fe18df930cc27497f9ae9fe08464274c3363f58c if you want me explain more about the script, please feel free let me know.

**Comment by y1275963** [comment]
Thanks a lot!

I really appreciate your help! May you have a nice day!

Yingjie

**Comment by haoel** [comment]
You are welcome!
