### ISSUE TITLE
[TransposeFile.sh] Memory Limit Exceeded

### ISSUE THREAD

**Issue by childe** [haoel/leetcode#67]
我的思路是:
如果有N列, 就循环N次, 每次把第i列打印出来.
```sh
read -a array <<< $(head -n1 file.txt)
for index in "${!array[@]}"
do
    awk '{if (NR==1) space=""; else space=" "} {printf "%s%s",space,$'$((1+index))'} END {printf "\n"}' file.txt
done
```
但是报错Memory Limit Exceeded.

看[你的代码](https://github.com/haoel/leetcode/blob/407b5bae7b4905f5d7de88d93c8aba6d9dd16abf/shell/TransposeFile.sh)是要把整个文件都写入s这个数组. 感觉内存使用上不会更少?

为什么我的回答报了"Memory Limit Exceeded", 这个报错到底代表什么? 
[这个题目的讨论区](https://leetcode.com/discuss/questions/oj/transpose-file)也有不少人有这个疑惑, 但还没有回答.
我只是直觉上觉得awk应该是读一行然后处理再读下一行. 为什么反而我的代码出错了呢?  耗哥能否帮忙解疑?

**Comment by haoel** [comment]
其实，awk ... file.txt就已经把file.txt整体读到内存了。另外，你的程序在for循环里读了好多次文件。

**Comment by childe** [comment]
懂了, 多谢.
